### PR TITLE
Hyper.sh Integration

### PR DESCRIPTION
**Pull request by LFlare**
# Hyper.sh Integration PR
Hello,

This PR will hopefully serve to integrate [Hyper.sh](https://hyper.sh) into Drone through this repository. It is however, incomplete and very prone to breaking. There are some bugs that still exists as of ef37d3f and are also listed below.

## Bugs & Fixes
- [ ] Cache is broken - Hyper.sh does not support host directory mounting
- [ ] Services semi-broken - Unable to find services based on hostname(?)
- [ ] "repository name must be canonical" - Not sure what causes it
- [x] `plugins/docker` causes cgroup errors - Image must be rebuilt from `hyperhq/docker-in-hyper` rather than `docker:dind`. This one will depend on drone-plugins/drone-docker#148
- [x] Environment invalid

### CODE REVIEW

**Comment by tboerger** [comment]
For hyper you have to provide a container size, this is part of the hyper api. You should define a default size that can be overwritten for each step

**Comment by LFlare** [comment]
@tboerger, that's fine and all, it's rather self-explanatory but I still do not really know where I can define the container size. The current API documents are also outdated by a year so I'm lost.

**Comment by tboerger** [comment]
I'm pretty sure you will find the required attributes within https://godoc.org/github.com/hyperhq/hyper-api/types

**Comment by LFlare** [comment]
@tboerger, you are right, I found https://godoc.org/github.com/hyperhq/hyper-api/types#Func, but it doesn't plug into any function I can find relating to the container creation process. Even so, it should also automatically create a container with a size of `s4` but that still brings about a point of the fact there's no function that takes in the struct `Func`.

**Comment by tboerger** [comment]
@Gnep you choose an uncommon name for this label :)

**Comment by Gnep** [comment]
Yeah, I knew .... :(

One question: AFAIK, Drone agents need to mount docker.sock into the container, where it access the docker api. Since Hyper.sh doesn't support docker.sock yet, did you change the agent code, to make it access Hyper API directly? If so, the compose file needs to be updated for a Hyper-specific version? http://docs.drone.io/installation/

**Comment by Jimmy-Xu** [comment]
@LFlare 

For this line: `_, err := e.client.ContainerCreate(ctx, config, hostConfig, nil, proc.Name)`

the `config` struct example:
```
{
  "Hostname": "",
  "Domainname": "",
  "User": "",
  "AttachStdin": false,
  "AttachStdout": true,
  "AttachStderr": true,
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": [],
  "Cmd": null,
  "Image": "ubuntu",
  "Volumes": {},
  "WorkingDir": "",
  "Entrypoint": null,
  "OnBuild": null,
  "Labels": {
    "sh_hyper_instancetype": "s4"
  },
  "StopSignal": "SIGTERM"
}

```

the `hostConfig` struct example:
```

{
  "AutoRemove": false,
  "Binds": null,
  "BlkioDeviceReadBps": null,
  "BlkioDeviceReadIOps": null,
  "BlkioDeviceWriteBps": null,
  "BlkioDeviceWriteIOps": null,
  "BlkioWeight": 0,
  "BlkioWeightDevice": null,
  "CapAdd": null,
  "CapDrop": null,
  "Cgroup": "",
  "CgroupParent": "",
  "ConsoleSize": [
    0,
    0
  ],
  "ContainerIDFile": "",
  "CpuCount": 0,
  "CpuPercent": 0,
  "CpuPeriod": 0,
  "CpuQuota": 0,
  "CpuShares": 0,
  "CpusetCpus": "",
  "CpusetMems": "",
  "Devices": [],
  "DiskQuota": 0,
  "Dns": [],
  "DnsOptions": [],
  "DnsSearch": [],
  "ExtraHosts": null,
  "GroupAdd": null,
  "IOMaximumBandwidth": 0,
  "IOMaximumIOps": 0,
  "IpcMode": "",
  "Isolation": "",
  "KernelMemory": 0,
  "Links": null,
  "LogConfig": {
    "Config": {},
    "Type": ""
  },
  "Memory": 0,
  "MemoryReservation": 0,
  "MemorySwap": 0,
  "MemorySwappiness": -1,
  "NetworkMode": "bridge",
  "OomKillDisable": false,
  "OomScoreAdj": 0,
  "PidMode": "",
  "PidsLimit": 0,
  "PortBindings": {},
  "Privileged": false,
  "PublishAllPorts": false,
  "ReadonlyRootfs": false,
  "RestartPolicy": {
    "MaximumRetryCount": 0,
    "Name": "no"
  },
  "SecurityOpt": null,
  "ShmSize": 0,
  "StorageOpt": null,
  "UTSMode": "",
  "Ulimits": null,
  "UsernsMode": "",
  "VolumeDriver": "",
  "VolumesFrom": null
}
```

FYI:  https://github.com/hyperhq/hypercli/blob/master/api/client/create.go#L227 
Hope it helpful.

**Comment by LFlare** [comment]
@Gnep Thanks for the small hint, I've managed to get the container created but now there's another new bug with the host folder mounting.

```
~/go/src/github.com/cncd/pipeline/samples/sample_7_redis$ ../../pipec/pipec exec
proc "pipeline_services_0" started
proc "pipeline_services_1" started
Error response from daemon: Bind host directory is not supported in current release
```

**Comment by tboerger** [comment]
@Gnep the docker backend would use the docker socket, the hyper.sh implementation should directly use the hyper api.

**Comment by Jimmy-Xu** [comment]
@LFlare 
The error message `Volume(pipeline-default) has been bind to another container`  means that a volume can be bound to one container at the same time.

`hyper rm` has a parameter `-v`, it can delete the volume when delete container.
FYI: https://docs.hyper.sh/Reference/API/2016-04-04%20[Ver.%201.23]/Container/remove.html

**Comment by LFlare** [comment]
@Jimmy-Xu, I don't think the volume should be removed. It's part of the pipeline and acts as a shared folder among the steps. I've temporarily pushed a fix that basically deletes the previous step's container before starting the next container such that the volume can be remounted by the next container.

**Comment by tboerger** [comment]
So it looks like the entire parallel execution groups won't work on hyper.sh?

**Comment by LFlare** [comment]
@tboerger, that appears to be the case. I'm thinking of a work around using snapshots, where each stage's volume is snapshotted and each subsequent stage's step recreates the volumes from the snapshot. Not sure, would love your input on how this can be accomplished.

**Comment by Gnep** [comment]
Or, you can detach the volume from the previous container by "rm" the container, and re-attach to the new container.

We also have a NFS feature: 
$ hyper run --name mycontainer -d -v /data1 -v /data2 hyperhq/nfs-server
$ hyper run -d --name test1 --volumes-from mycontainer busybox
$ hyper run -d --name test2 --volumes-from mycontainer busybox

**Comment by LFlare** [comment]
Shared volume has been implemented through the method @Gnep described but there's still the host directory mounting giving issues. This affects things like caches.

**Comment by tboerger** [comment]
The build jobs don't need host mounts for cache, it's only required if a repo is trusted and defines some host mounts like the volume cache plugin.

**Comment by LFlare** [comment]
An additional note, attempting to build Drone with this has led to the error message `Error response from daemon: Environment is invalid, should be [A-Za-z_][A-Za-z0-9_]*`. I have no idea what causes this and I'm frustrated to no ends, since the current state of this PR should suffice for my needs but now I got another bug that I have no idea what's causing it to happen or what.

Especially when my `.drone.yml` merely contains the following,

```
pipeline:
    download:
        image: arm32v6/alpine
        commands:
            - apk --update upgrade
            - apk add git
            - git clone https://github.com/xinetd-org/xinetd

    compile:
        image: lflare/alpine:arm32_x86-64
        commands:
            - export CFLAGS="-I/usr/include/tirpc -L/usr/lib"
            - export LIBS="-ltirpc"
            - apk --update upgrade
            - apk add alpine-sdk libtirpc-dev
            - cd xinetd
            - ./configure --with-loadavg
            - sed -i -e "s/exec_server/child_process/" xinetd/builtins.c
            - sed -i -e "/register unsigned count/s/register//" xinetd/itox.c
            - sed -i -e "/#define rlim_t long long/d" libs/include/config.h
            - make
            - mv xinetd/xinetd ../xinetd.bin

    publish:
        image: plugins/docker
        tags: [latest, arm32_x86-64]
        repo: lflare/xinetd
        secrets: [docker_username, docker_password]
```

Attempting to debug this on `pipec` did not give me any errors but attempting to run builds over Drone failed to no ends. I'm frustrated.

**Comment by carmark** [comment]
Hello @LFlare 

The environment of `"DRONE_COMMIT_MESSAGE=Full compilation & multistep\n"` is invalid, you have to make sure the environment does not have space.

**Comment by LFlare** [comment]
@carmark, No spaces in between the messages or no newlines?

**Comment by carmark** [comment]
Yes, could you please convert it to another character and try it again?

**Comment by tboerger** [comment]
If environment variables can't include whitespaces it's pretty useless

**Comment by carmark** [comment]
@tboerger @LFlare I double check the environment verify, spaces are allowed, but newlines(`\n`) will cause this issue.  Could you please remove it?

**Comment by LFlare** [comment]
@carmark, Much appreciated, this is now fixed.

**Comment by LFlare** [comment]
Also included a patch to allow for custom container sizing, defaulting to `s4`.

**Pull request closed without merging**
