### PR TITLE
fix wrong default branch of repo.

### PR DESCRIPTION
**Pull request by appleboy**
cc @bradrydzewski

### CODE REVIEW

**Comment by appleboy** [comment]
@bradrydzewski Please help to take a look. ref: https://github.com/drone-plugins/drone-docker/pull/160

**Comment by appleboy** [comment]
@bradrydzewski I will update the vendor in `drone/drone` repo. Thanks 👍

**Comment by bradrydzewski** [comment]
I will be implementing https://github.com/cncd/pipeline/issues/28 tomorrow and am planning to update the vendor directory as well

**Comment by appleboy** [comment]
@bradrydzewski OK. I closed my PR in `drone/drone`

**Pull request merged**
