### PR TITLE
Add ability to not attach networks to a pipeline step

### PR DESCRIPTION
**Pull request by jmccann**
This provides the ability to not attach pipeline networks to a step, e.g.

```diff
pipeline:
  docker:
    image: plugins/docker
    repo: drone/drone
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
+   disable_networks: true
```

This is in support of https://github.com/drone/drone/issues/2132

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@jmccann the goal with https://github.com/drone/drone/issues/2132 would be to use the default bridge network, but still perform aliasing so that we can still connect with the services by hostname.

In this case if you do not need aliasing and just want to the default bridge network, you could add the following to your yaml configuration:

```
pipeline:
  step:
    image: foo
   network_mode: bridge
```

So if you are up for it, would love to get the services aliased when using the bridge network. And then perhaps we use an environment variable to dictate which behavior is preferred (create per-pipeline bridge network vs using default bridge).

Let me know your thoughts. Thanks :)

**Comment by jmccann** [comment]
So I tried `network_mode` and it requires `privileged` for the repo.  Whereas the solution I have is "safer" and wouldn't require me to give everyone `privileged`.

As for what is really trying to be addressed in https://github.com/drone/drone/issues/2132 I guess I misunderstood it.  I can maybe try to work on that ... I'll take a look and see how hard it'd be for me.

**Comment by bradrydzewski** [comment]
@jmccann good point. We could alter the linter to allow `network_mode` when set to `bridge` or `none` since those are safe values. Not sure if that would solve for your particular issue?

With https://github.com/drone/drone/issues/2132 I was trying to solve the issue that on some kubernetes installs, using custom bridge networks does not inherit the host machines DNS which causes issues for a lot of people.

**Comment by teodor-pripoae** [comment]
Hi,

Any new info regarding this issue ?

We are using docker with ufw and we are setting iptables rules as in [this comment](https://github.com/moby/moby/issues/4737#issuecomment-280668828). The problem is that drone is creating a new network for each build and our containers do not have internet access without adding the postrouting rule:

```
*nat
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING ! -o <network_name> -s <cidr> -j MASQUERADE
COMMIT
```

**Comment by jmccann** [comment]
Closing this as I don't need it anymore and it's stale

**Pull request closed without merging**
