### PR TITLE
Allow network_mode to be used in a step

### PR DESCRIPTION
**Pull request by Gazer**
With network mode we can reuse a network defined by another container (or the host itself), like a container connected
to a VPN. This is useful for the case that you should connect through a VPN to perform a deploy.

Because network_mode use an already created network, we can't use services on this build step. All custom networks
are disabled if network_mode is present.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
This looks great. Some minor feedback and then we can get this merged.

First is that we need to add a check to the linter (see [linter.go](https://github.com/cncd/pipeline/blob/master/pipeline/frontend/yaml/linter/linter.go#L68)) to ensure only trusted builds can set the network mode. Unfortunately network mode could be used to gain access to networks that the container should otherwise not have access to, so we need to put some restrictions in place.

```
	if len(c.NetworkMode) != 0 {
		return fmt.Errorf("Insufficient privileges to use network_mode")
	}
```

Second is to run gofmt on the code which will automatically format based on the standard Go community style guidelines. See https://blog.golang.org/go-fmt-your-code

Otherwise everything looks really good. Great job :)

**Comment by Gazer** [comment]
> First is that we need to add a check to the linter (see linter.go) to ensure only trusted builds can set the network mode

If I understand correctly the check is already done on [line 87](https://github.com/cncd/pipeline/blob/master/pipeline/frontend/yaml/linter/linter.go#L87). That should be enough? I can add the missing test if helps.

> Second is to run gofmt on the code which will automatically

Thanks!, It was really frustrating to try formatting the first commit correctly. This saves me a lot of time :D. I've installed go-plus on Atom now.

**Comment by bradrydzewski** [comment]
> If I understand correctly the check is already done on line 87. That should be enough? I can add the missing test if helps.

yes, you are right

**Comment by bradrydzewski** [comment]
LGTM once formatted. I will then update the drone core dependencies. You changes will then be available in the `drone/drone:latest` image until we tag our next release.

**Comment by Gazer** [comment]
Done!, formatted and test added! Thank you!

> You changes will then be available in the drone/drone:latest image until we tag our next release.

Excelente!

**Comment by bradrydzewski** [comment]
ok, change is available now in `drone/drone:latest` :)

**Pull request merged**
