### PR TITLE
Added framework for hyper.sh integration

### PR DESCRIPTION
**Pull request by LFlare**
Hello,

This PR is in reference to my older PR #24, which I closed because it was getting messy and it's primary purpose was during development of the hyper.sh integration. Now that I've integrated the API in a way that suits my needs, I'm submitting this _finished_ code as a PR towards the master branch in hopes that @tboerger or @bradrydzewski would review it for final merging.

Other than in the case of serious bugs or world-apocalyptic events, I would most likely not improve on the current codebase any longer, considering that my Golang skills are that of infancy.

Thank you for reading my wall of text.

### CODE REVIEW

**Comment by tboerger** [comment]
For the future you can reduce the noise and spreading history across multiple prs with squashing commits and doing a force push

**Comment by LFlare** [comment]
@tboerger I've done that but I felt that it would interrupt development history too much, so I decided to create a brand new PR. Unlike the previous, this I feel, is complete.

**Comment by Gnep** [comment]
Guys, pls keep me posted once it is merged into Drone. Would love to give a run with the new release. Thanks!

**Comment by LFlare** [comment]
@Gnep I think my integration is fairly solid but I would love if @tboerger or @bradrydzewski would give it a onceover before merging ^_^

**Comment by LFlare** [comment]
Hello it's been nearly 3 weeks, can I get a response back whether this PR is welcomed? @tboerger @bradrydzewski.

CC. @Gnep

**Comment by ddavidebor** [comment]
Hi guys, i'm really looking foward for this functionality to be added to drone and this PR being merged :-)

**Comment by LFlare** [comment]
@tboerger, @bradrydzewski, could this PR be reviewed soon?

**Comment by LFlare** [comment]
@tboerger, @bradrydzewski, could this PR be reviewed soon?

**Comment by tboerger** [comment]
It's up to @bradrydzewski

**Comment by bradrydzewski** [comment]
0.9 will include a pluggable runtime engine. Drone will provide a default implementation (Docker) and will allow additional runtime engines using [Go plugins](https://golang.org/pkg/plugin/). This should be in place early December. It would work something like this:

```
docker run \
  -v /path/to/plugin.so:/usr/local/include/hyper.so \
  -e DRONE_RUNTIME=/usr/local/include/hyper.so \
  drone/drone
```

This means you will be able to publish your hyper integration as a shared plugin, which others can download and then use with their drone installation.

**Comment by LFlare** [comment]
@bradrydzewski, I assume that feature is available now?

**Comment by bradrydzewski** [comment]
yes see https://github.com/drone/drone-runtime#runtime-engines

**Comment by bradrydzewski** [comment]
closing this in favor of plugins for the drone-runtime:
https://github.com/drone/drone-runtime#runtime-engines 

example plugin: 
https://github.com/drone/drone-kubernetes-runtime

**Pull request closed without merging**
