### PR TITLE
Use stream to handle worker disconnection and job failure

### PR DESCRIPTION
**Pull request by bclermont**
I heavily use gRPC and depends on Drone to build my stack.

As we suffers a lot of build that never are marked as failed.
and stuck workers, I looked at Drone code.

In my own gRPC applications, we used to experience a lot of similar case with client stuck and only disconnect after few hours, if not that need restart. and server that figure state of something with difficulty.
We solved all of them and everything is very stable, my experience can be useful here.

I noticed that this gRPC API is designed to be like a REST over gRPC and not designed to benefit from nice gRPC features (stream).

What if the API is changed like this PR. and have a drone worker open a single stream and maintains it.
and server keep the state of that worker. and if the stream is disconnected (maybe worker panic, worker `kill -9`, server died, etc), then server can mark job as failed.

and as long as the stream is kept open, you know that that the worker is online.

### CODE REVIEW

**Comment by aleccunningham** [comment]
Oh sweet! Yeah, I just recently walked through the backend code and realized that drone is using jsonrpc2 with their rpc calls. This change would touch a *lot* of the code base though.

**Comment by bclermont** [comment]
@aleccunningham can just switch to golang and grpc in browser with https://github.com/gopherjs/gopherjs

**Comment by aleccunningham** [comment]
@bclermont have you seen this PR? https://github.com/drone/drone/pull/2358

**Comment by bradrydzewski** [comment]
> Yeah, I just recently walked through the backend code and realized that drone is using jsonrpc2 with their rpc calls.

just an fyi, drone does not use jsonrpc2. The `rpc` package in this repository supports both a jsonrpc2 and a grpc implementation. The drone project officially switched over to the grpc implementation some time ago.

**Comment by bradrydzewski** [comment]
While I appreciate the discussion and sample code in this pull request, condensing the service to a single function call that uses a stream does not seem like an idiomatic approach. The design we are using does not emulate REST, it emulates function calls.

Every grpc function call is multiplexed over a single, persistent http2 connection. Streams would be multiplexed over the same http2 connection. So I am not sure this would improve connectivity issues, since the same underlying connection would still be used.

Per many of the [grpc guides](https://blog.gopheracademy.com/advent-2017/go-grpc-beyond-basics/) you will notice that services are defined with multiple function calls, as opposed to a single function call with a string and enumerations. For example:

```
service GoReleaseService {
    rpc GetReleaseInfo(GetReleaseInfoRequest) returns (ReleaseInfo) {}
    rpc ListReleases(ListReleasesRequest) returns (ListReleasesResponse) {}
}
```

and 

```
// The Customer service definition.
service Customer {   
  // Get all Customers with filter - A server-to-client streaming RPC.
  rpc GetCustomers(CustomerFilter) returns (stream CustomerRequest) {}
  // Create a new Customer - A simple RPC 
  rpc CreateCustomer (CustomerRequest) returns (CustomerResponse) {}
}
```

With that being said, there may be ways we can use streams to reduce overhead when streaming the logs to the server. But this would involve modifying a single function call to use a stream. But again, I definitely appreciate the thought and discussion, and I definitely want to continue to work toward improving connectivity and reliability.

**Comment by bclermont** [comment]
> So I am not sure this would improve connectivity issues

when grpc stream close, you need the worked had been disconnected and can consider the job failed

**Comment by bradrydzewski** [comment]
> when grpc stream close, you need the worked had been disconnected and can consider the job failed

grpc is able to usually able to automatically reconnect if, for whatever reason, there is a brief network interruption. We have code to handle reconnect and retry. We have a lot of corporate installations of drone that experience frequent, small network disruptions, so reconnect and retry is preferred when the network disconnects.

If the network becomes unavailable we typically see the below logs, and when the connection is re-established, we are able to reconnect and resume. 

```
INFO: 2018/03/18 21:17:16 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:9000: getsockopt: connection refused"; Reconnecting to {localhost:9000 <nil>}
INFO: 2018/03/18 21:17:17 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:9000: getsockopt: connection refused"; Reconnecting to {localhost:9000 <nil>}
```

In fact, in the majority of cases where it looks like builds are frozen or stuck, it is because of a reverse proxy or load balancer. Once should not be using grpc with a reverse proxy, and load balancing disconnections are typically the result of inactivity which can be fixed with the keepalive settings.

So I'm not sure we need to drastically change anything about the grpc implementation to solve this problem. I think instead we probably need a few minor tweaks to the connection configuration and retry logic.

**Comment by bclermont** [comment]
What I mean is what if you:

- Worker create new stream
- Worker in stream send `InitRequest`
- Server return `Reply`
- Worker send `WaitRequest`
... and typical workflow of a worker <-> server

the stream is a single "session" (connect, wait for build job, perform build job, send results, close)
if for any reason, at any time the stream close, then build had failed

you don't have to handle any retry logic

**Pull request closed without merging**
