### PR TITLE
Resource limits

### PR DESCRIPTION
**Pull request by jmccann**
Add option to compiler to add resource limits

### CODE REVIEW

**Comment by bradrydzewski** [comment]
thanks!

**Comment by tonglil** [comment]
@jmccann can I ask what kind of units are these? I tried to set `DRONE_LIMIT_MEM` to `2g` (based on docker's docs) but it only accepts integers. Couldn't find where the value is set on the container in https://github.com/cncd/pipeline/ though.

**Comment by bradrydzewski** [comment]
they are bytes, so you would need to set `DRONE_LIMIT_MEM=2000000000` :)

**Comment by tonglil** [comment]
Thank you. Will document!

**Pull request merged**
